[package]
name = "gzhu-typst-thesis"
version = "0.4.0"
entrypoint = "lib.typ"
repository = "https://github.com/bigsaltyfishes/gzhu-typst-thesis"
authors = ["bigsaltyfishes <bigsaltyfishes@gmail.com>"]
license = "MIT"
description = "广州大学学位论文 Typst 模板，A Typst template for GZHU thesis"
keywords = ["GZHU", "thesis", "typst"]
categories = ["thesis"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
