stages:
    - check
    - release

# each merge request are required to ensure compiling the `.typ`s file successfully.
check-merge-request:
  stage: check
  image: rust
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  cache:
    paths:
      - $CARGO_HOME
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - cargo install typst-cli git-cliff sd
  script:
    - typst compile --root=$CI_PROJECT_DIR --font-path=$CI_PROJECT_DIR/fonts $CI_PROJECT_DIR/template/thesis.typ

check-default-branch:
  stage: check
  image: rust
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  cache:
    paths:
      - $CARGO_HOME
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - cargo install typst-cli git-cliff sd
  script:
    - typst compile --root=$CI_PROJECT_DIR --font-path=$CI_PROJECT_DIR/fonts $CI_PROJECT_DIR/template/thesis.typ $CI_PROJECT_DIR/thesis_preview.pdf
  # TODO(#1): the preview pdf should be generated by template repo
  # artifacts:
  #   paths:
  #     - $CI_PROJECT_DIR/thesis_preview.pdf

gitlab-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "releasing $CI_COMMIT_TAG on GitLab!"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && '$CI_COMMIT_TAG'
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG_MESSAGE'
