image: rust
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - $CARGO_HOME

stages:
    - check
    - release

before_script:
  - export PATH="$PATH:$CARGO_HOME/bin"
  - cargo install typst-cli git-cliff

build:
  stage: check
  script:
    - typst compile --root=$CI_PROJECT_DIR --font-path=$CI_PROJECT_DIR/fonts $CI_PROJECT_DIR/template/thesis.typ
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

gitlab-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - mkdir prview && typst compile --root=. --font-path=fonts template/thesis.typ prview/thesis.pdf
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
