on:
  pull_request:
    branches:
      - main

jobs:
  typst:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    #     arch: [x86_64, aarch64]
    steps:
      - id: toolchain
        uses: dtolnay/rust-toolchain@stable

      # Check if there are caches before. If there is some, the typst-cli
      # should be installed.
      - id: restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/bin/
          key: cargo-${{ steps.toolchain.outputs.name }}

      - name: Install Typst
        if: steps.restore.outputs.cache-hit != 'true'
        run: cargo install typst-cli

      - name: Cache Cargo
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ steps.toolchain.outputs.name }}

  check_template:
    needs:
      - typst
    runs-on: ubuntu-latest
    steps:
      # After the `typst` job, there should be typst-cli command in cache
      - name: Restore Typst
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
          key: cargo-${{ steps.toolchain.outputs.name }}

      # Check but not save. All pull requests to the main branch are considered
      # as single-feature of the whole template.
      - name: Check the template
        run: >
          typst compile
            --root=.
            --font-path=./fonts
            ./template/thesis.typ
            ./thesis_preview.pdf
